name: Publish to TestPyPI

on:
    push:
        branches:
            - main
    release:
        # do not run when created/draft, only when finalised
        types: [published]
    workflow_dispatch:
        inputs:
            version:
                description: "Unicode version number"
                required: true
                type: string
            dry-run:
                description: "Perform a dry run without actual publishing"
                default: true
                type: boolean
            official-publish:
                description: "Official publish to PyPI (not TestPyPI)"
                default: false
                type: boolean

jobs:
    build:
        name: Build distribution
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        steps:
            - uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"
                  cache: "pip"

            - name: Install requirements
              run: pip install -r requirements-dev.txt

            - name: Set version and update blocks.py data file [manual run]
              if: |-
                ${{ 
                  github.event_name == 'workflow_dispatch' && 
                  github.event.inputs.version != '' && 
                  github.event.inputs.official-publish == 'false' 
                }}
              run: |
                  python3 bump_pyproject_version.py "${{ github.event.inputs.version }}"
                  python3 build_blocks.py

            - name: Update blocks.py for testing [on push]
              if: ${{ github.event_name == 'push' }}
              run: |
                  python3 build_blocks.py

            - name: Commit version update
              if: |-
                ${{ 
                  github.event_name == 'workflow_dispatch' &&
                  github.event.inputs.version != '' && 
                  github.event.inputs.official-publish == 'false' && 
                  github.event.inputs.dry-run == 'false' 
                }}
              uses: stefanzweifel/git-auto-commit-action@v7
              with:
                  commit_message: "Bump version to ${{ github.event.inputs.version }}"
                  branch: main
                  file_pattern: |-
                      src/unicode_blocks/blocks.py
                      pyproject.toml

            - name: Build the binary wheel and source tarball
              run: python3 -m build

            - name: Run tests
              run: |
                  pip install dist/*.whl
                  pytest tests/
                  python -m doctest README.md

            - name: Store the distribution packages
              uses: actions/upload-artifact@v4
              with:
                  name: python-package-distributions
                  path: dist/

    publish-to-testpypi:
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.official-publish == 'false' && github.event.inputs.dry-run == 'false' }}
        name: Publish Python distribution to Test PyPI
        needs:
            - build
        runs-on: ubuntu-latest

        environment:
            name: testpypi
            url: https://test.pypi.org/p/unicode-blocks-py

        permissions:
            id-token: write # IMPORTANT: mandatory for trusted publishing

        steps:
            - name: Download all the dists
              uses: actions/download-artifact@v4
              with:
                  name: python-package-distributions
                  path: dist/
            - name: Publish distribution ðŸ“¦ to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/
                  verbose: true

    publish-to-pypi:
        name: Publish official Python distribution to PyPI
        needs:
            - build
        runs-on: ubuntu-latest
        if: |-
            ${{ 
              (github.event_name == 'release') || 
              (github.event_name == 'workflow_dispatch' && github.event.inputs.official-publish == 'true' && github.event.inputs.dry-run == 'false') 
            }}

        environment:
            name: pypi
            url: https://pypi.org/project/unicode-blocks-py

        permissions:
            id-token: write # IMPORTANT: mandatory for trusted publishing

        steps:
            - name: Download all the dists
              uses: actions/download-artifact@v4
              with:
                  name: python-package-distributions
                  path: dist/
            - name: Publish distribution ðŸ“¦ to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
